steps:
  - id: 'app-source-code'
    name: 'alpine'
    waitFor: ['-']
    volumes:
      - name: 'source-code'
        path: '/build/source-code'
    args: ['cp', '-T', '-r', './', '/build/source-code']

  - id: app-docker-image-build
    name: gcr.io/kaniko-project/executor
    waitFor:
      - 'app-source-code'
    volumes:
      - name: 'source-code'
        path: '/build/source-code'
    args: [
      "--dockerfile=.devops/dockerfiles/Dockerfile",
      "--context=/build/source-code",
      "--destination=$_CONTAINER_REGISTRY/$_IMAGE_NAME:$SHORT_SHA",
      "--destination=$_CONTAINER_REGISTRY/$_IMAGE_NAME:latest"
    ]

  - id: 'app-deploy-run'
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - beta
      - run
      - deploy
      - $_IMAGE_NAME
      - --image
      - $_CONTAINER_REGISTRY/$_IMAGE_NAME:$SHORT_SHA
      - --region
      - $_REGION_NAME
